---
- name: Run commands on target servers
  hosts: all
  become: yes
  tasks:
    - name: Run a shell command
      shell: |
        sudo ufw allow 6443
        sudo ufw reload

    - name: Install a package
      apt:
        name: nfs-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Run a shell command
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1 EOF
        sysctl --system
        modprobe br_netfilter
