---
- name: Run commands on target servers
  hosts: all
  become: yes
  tasks:
    - name: Run a shell command
      shell: |
        sudo ufw allow 6443
        sudo ufw reload

    - name: Install a package
      apt:
        name: nfs-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Run a shell command
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1 EOF
        sysctl --system
        modprobe br_netfilter
        cd /usr/local
        wget https://github.com/containerd/containerd/releases/download/v1.7.15/containerd-1.7.15-linux-amd64.tar.gz
        tar Cxzvf /usr/local containerd-1.7.15-linux-amd64.tar.gz
        cd /usr/lib/systemd/system/
        wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        systemctl daemon-reload
        systemctl enable --now containerd
        cd /usr/local
        wget https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
        install -m 755 runc.amd64 /usr/local/sbin/runc
        mkdir /etc/containerd
        touch /etc/containerd/config.toml
        chmod 777 /etc/containerd/config.toml
        containerd config default > /etc/containerd/config.toml
