- name: test
  hosts: all
  become: yes
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Update repositories cache and install "htop" package
      become: true
      ansible.builtin.apt:
        name: htop
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required
