---
- name: Install Prometheus Node Exporter
  hosts: all
  become: yes
  become_method: sudo

  vars:
    node_exporter_version: '1.8.1'
    node_exporter_user: 'node_exporter'
    node_exporter_group: 'node_exporter'

  tasks:
    - name: Create node_exporter user
      user:
        name: "{{ node_exporter_user }}"
        shell: /usr/sbin/nologin

    - name: Download Node Exporter
      shell: | 
        cd /usr/local/bin
        wget "https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz"
  
    - name: Extract Node Exporter
      shell: |
        cd /usr/local/bin
        tar xzf /usr/local/bin/node_exporter-1.8.1.linux-amd64.tar.gz

    #- name: rename directory
    #  command: mv /usr/local/bin/node_exporter /usr/local/bin/node_exporter

    - name: Set permissions on Node Exporter binary
      file:
        path: /usr/local/bin/node_exporter-1.8.1.linux-amd64
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: '0755'

    - name: Create systemd service file for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ node_exporter_user }}
          Group={{ node_exporter_group }}
          Type=simple
          ExecStart=/usr/local/bin/node_exporter-1.8.1.linux-amd64/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to read new service file
      command: systemctl daemon-reload

    - name: Enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
