---
- name: Install Prometheus Node Exporter
  hosts: all
  become: yes

  vars:
    node_exporter_version: '1.8.1'
    node_exporter_user: 'node_exporter'
    node_exporter_group: 'node_exporter'

  tasks:
    - name: Create node_exporter user
      user:
        name: "{{ node_exporter_user }}"
        shell: /usr/sbin/nologin

    - name: Download Node Exporter
      command: wget -0 /tmp/node_exporter.tar.gz "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  
    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        creates: "/usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

    - name: Move Node Exporter binary
      command: mv /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/node_exporter
      args:
        creates: /usr/local/bin/node_exporter

    - name: Set permissions on Node Exporter binary
      file:
        path: /usr/local/bin/node_exporter
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: '0755'

    - name: Create systemd service file for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ node_exporter_user }}
          Group={{ node_exporter_group }}
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to read new service file
      command: systemctl daemon-reload

    - name: Enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
